Update from Original (#1)
* forcing use of standard module for Expand-Archive

* flipped a couple lines to fix debug output error

* skipping check of sysmondrv.sys version 

12.0 package has wrong version metadata for that file

* debug text

* text output fix

* extra checks and more detailed progress output

* DBG is now a parameter

* Install sysmon64 bit on 64bit machines.

* comment line edits

* check for SO and WazMgr and add DBG parm

* add -local groups and org group

* added -local and org groups

* added -local and org groups

* added -local and org groups

* document DBG better

* Create bnc-siem.suite.sh

* Create bnc-siem.suite.ps1

* Update bnc-siem.suite.sh

Co-authored-by: BarnumD <daveorders@thebarnums.com>
Co-authored-by: Kevin Branch <kevin@branchnetconsulting.com>
Co-authored-by: Ken Fredericksen <ken@branchnetconsulting.com>

diff --git a/check-wazuh-linux-agent-suite b/check-wazuh-linux-agent-suite
--- a/check-wazuh-linux-agent-suite
+++ b/check-wazuh-linux-agent-suite
@@ -22,6 +22,7 @@
 # -WazuhGroups          Comma separated list of optional extra Wazuh agent groups. No spaces. Put whole list in quotes. Use "" to expect zero extra groups.
 #                       If not specified, agent group membership will not be checked at all.
 # -SkipOsquery          Set this flag to skip the default examination of Osquery and assume Osquery is not installed on agent. (Optional)
+# -DBG			Show debug output
 # -help                 Show command syntax
 #
 # Sample way to fetch and use this script:
@@ -32,13 +33,10 @@
 # echo "Exit code: $?"
 #
 
-# Uncomment this line to enable debug output, otherwise there should be no output other than the exit code.
-#DBG=1
-
 function show_usage() {
    LBLU='\033[1;34m'
    NC='\033[0m'
-   printf "\nCommand syntax:\n   $0 -WazuhMgr ${LBLU}WAZUH_MANAGER${NC} [-WazuhRegMgr ${LBLU}WAZUH_REGISTRATION_MANAGER${NC}] -WazuhVer ${LBLU}WAZUH_VERSION${NC} [-WazuhGroups {${LBLU}LIST_OF_EXTRA_GROUPS${NC} | \"\"}] {-OsqueryVer ${LBLU}OSQUERY_VERSION${NC} | -SkipOsquery} [-help]\n\n"
+   printf "\nCommand syntax:\n   $0 -WazuhMgr ${LBLU}WAZUH_MANAGER${NC} [-WazuhRegMgr ${LBLU}WAZUH_REGISTRATION_MANAGER${NC}] -WazuhVer ${LBLU}WAZUH_VERSION${NC} [-WazuhGroups {${LBLU}LIST_OF_EXTRA_GROUPS${NC} | \"\"}] {-OsqueryVer ${LBLU}OSQUERY_VERSION${NC} | -SkipOsquery} [-DBG] [-help]\n\n"
    printf "Examples:\n   $0 -WazuhMgr ${LBLU}siem.company.org${NC} -WazuhVer ${LBLU}3.13.1${NC} -WazuhGroups ${LBLU}finance,denver${NC} -OsqueryVer ${LBLU}3.4.0${NC}\n"
    printf "   $0 -WazuhMgr ${LBLU}siem.company.org${NC} -WazuhRegMgr ${LBLU}siem-reg.company.org${NC} -WazuhVer ${LBLU}3.13.1${NC} -WazuhGroups ${LBLU}finance,denver${NC} -SkipOsquery\n"
    printf "   $0 -WazuhMgr ${LBLU}siem.company.org${NC} -WazuhVer ${LBLU}3.13.1${NC} -OsqueryVer ${LBLU}3.4.0${NC}\n\n"
@@ -117,12 +115,22 @@ while [ "$1" != "" ]; do
       -help )         show_usage
                       exit 2
                       ;;
+      -DBG )          DBG=1
+                      ;;
       * )             show_usage
                       exit 2
    esac
    shift
 done
 
+if [ -f /etc/nsm/securityonion.conf ]; then
+		if [ $DBG ]; then echo -e "\n*** This deploy script cannot be used on a system where Security Onion is installed."; fi
+		exit 2
+fi
+if [[ `grep server /etc/ossec-init.conf` ]]; then
+		if [ $DBG ]; then echo -e "\n*** This deploy script cannot be used on a system where Wazuh manager is already installed."; fi
+		exit 2
+fi
 if [ "$WazuhMgr" == "" ]; then
         echo -e "\n*** Must use '-WazuhMgr' to specify the FQDN or IP of the Wazuh manager to which the agent shall retain a connection."
         show_usage
@@ -165,7 +173,7 @@ fi
 # This needs to be refined, but reflects the Linux flavors I actually work with.
 # Do not perform agent group check if
 if [ "$WazuhGroups" != "#NOGROUP#" ]; then
-        WazuhGroupsPrefix="linux,"
+        WazuhGroupsPrefix="linux,linux-local,"
         if [[ -f /etc/os-release && `grep -i debian /etc/os-release` ]]; then
                 LinuxFamily="deb"
                 WazuhGroupsPrefix="${WazuhGroupsPrefix}ubuntu,"
@@ -174,9 +182,10 @@ if [ "$WazuhGroups" != "#NOGROUP#" ]; then
                 WazuhGroupsPrefix="${WazuhGroupsPrefix}centos,"
         fi
         if [ $SkipOsquery == 0 ]; then
-                WazuhGroupsPrefix="${WazuhGroupsPrefix}osquery,"
+                WazuhGroupsPrefix="${WazuhGroupsPrefix}osquery,osquery-local,"
         fi
-        WazuhGroups="${WazuhGroupsPrefix}$WazuhGroups"
+		WazuhGroupsPrefix="${WazuhGroupsPrefix}org,"
+		WazuhGroups="${WazuhGroupsPrefix}$WazuhGroups"
         # If there were no additional groups, strip off the trailing comma in the list.
         WazuhGroups=`echo $WazuhGroups | sed 's/,$//'`
         CURR_GROUPS=`echo \`grep "<\!-- Source file: " /var/ossec/etc/shared/merged.mg | cut -d" " -f4 | cut -d/ -f1 \` | sed 's/ /,/g'`
